name: Deploy Multiple Projects to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create build directory
        run: |
          mkdir -p build
          mkdir -p build/debug
          
          # Copy html_and_css project files
          cp -r html_and_css/project/buttons-collection/* build/buttons/
          cp -r html_and_css/project/blog-layout/* build/blog/
          cp -r html_and_css/project/landing-page/* build/landing/
          cp -r html_and_css/project/image-gallery/* build/gallery/
          cp -r html_and_css/project/profile-card/* build/profile/
          cp -r html_and_css/project/pricing-table/* build/pricing/
          
          # Copy html_and_css debug files
          cp -r html_and_css/debug/buttons-collection/* build/debug/buttons/
          cp -r html_and_css/debug/blog-layout/* build/debug/blog/
          cp -r html_and_css/debug/landing-page/* build/debug/landing/
          cp -r html_and_css/debug/image-gallery/* build/debug/gallery/
          cp -r html_and_css/debug/profile-card/* build/debug/profile/
          cp -r html_and_css/debug/pricing-table/* build/debug/pricing/
          
          # Create directories first
          mkdir -p build/buttons build/blog build/landing build/gallery build/profile build/pricing
          mkdir -p build/debug/buttons build/debug/blog build/debug/landing build/debug/gallery build/debug/profile build/debug/pricing
          
          # Copy index files
          cp html_and_css/debug/index.html build/debug/
          cp index.html build/
          cp -r assets build/ 2>/dev/null || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 